######################################################################
# Automatically generated by qmake (2.01a) Mon Jan 9 18:31:46 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . source
INCLUDEPATH += . source

# Input
HEADERS += source/mainWindow.h
SOURCES += source/mainWindow.cpp \
           source/searchFunctions.cpp \
           source/updateFunctions.cpp \
           source/YADSA.cpp
RESOURCES += YADSA.qrc
